### ISSUE TITLE
fill in start/end dates for each storm event

### ISSUE THREAD

**Issue by limnoliver** [limnoliver/GMIAAbs#17]
Noticed in Science Base data preparation that some start and end times for storms were missing. Track these down.

**Comment by limnoliver** [comment]
The samples with missing dates are all grab samples, so don't have an 'end time'. Pete noted these are often taken at the tail end of an event. Should we treat these the same @srcorsi-USGS? These are currently in the analysis, and I think are mostly COD samples.

**Comment by srcorsi-USGS** [comment]
That makes sense. These samples should be treated the same as other samples.
