### ISSUE TITLE
Which WQ vars to keep? 

### ISSUE THREAD

**Issue by limnoliver** [limnoliver/GMIAAbs#6]
Which water quality variables should be merged with absorbance data @srcorsi-USGS?
 To see which onces I'm currently using, see [these lines](https://github.com/limnoliver/GMIAAbs/blob/2b4c145af95c9301ab2f7655fbf864799702f9cf/scripts/1_munge/cleanWQdata.R#L18) in cleanWQdata.R

**Comment by srcorsi-USGS** [comment]
cod|bod|formate|acetate|glycol|potassium|sodium|ethylene|propylene|methyl
